name: Build All

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { name: "Scala", version: "2.13.8", binary-version: "2", java-version: "11", java-distribution: "temurin" }

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.scala.java-version }}
          distribution: ${{ matrix.scala.java-distribution }}

      - name: Cache SBT
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

      - name: Build for Scala ${{ matrix.scala.version }}
        run: .github/workflows/sbt-build-all.sh ${{ matrix.scala.version }}
